name: Build and Run

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with: 
          node-version: '14'

      - name: Install Dependncies
        run:  sudo npm install
        
      - name: tshirts fail
        run: |
          cd tshirts
          'node TshirtSizeTester.js'

      - name: misaligned fail
        run: |
          cd misaligned
          'node MisalignedColorPairTester.js'

      - name: alerter fail
        run: |
          cd alerter 
          'node NetworkAlerterTester.js'
        
